version: 0.0
os: linux
files:
  - source: \
    destination: c:\temp\webapp_5579
hooks:
  BeforeInstall:
    - location: pwfiles\deletewebsite.ps1
      timeout: 180
  AfterInstall:
    - location: pwfiles\installwebsite.ps1
      timeout: 180
  ValidateService:
    - location: pwfiles\valinstall.ps1
      timeout: 30